env: "docker"
http_server:
  address: "0.0.0.0:8081"
  timeout: 5s
  idle_timeout: 60s
postgresql:
  host: "db"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "subscriptions"
  sslmode: "disable"
