env: "local"
http_server:
  address: "localhost:8081"
  timeout: 5s
  idle_timeout: 60s
postgresql:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "subscriptions"
  sslmode: "disable"
